version: 2.1

jobs:
  ubuntu_bionic:
    description: A template for running liboqs-python tests on an OQS Ubuntu Bionic Docker Image
    docker:
      - image: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Clone liboqs
          command: git clone --branch main --single-branch --depth 1 https://github.com/open-quantum-safe/liboqs
          working_directory: /root
      - run:
          name: Build liboqs
          command: mkdir build && cd build && cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON && ninja
          working_directory: /root/liboqs
      - run:
          name: Run liboqs-python unit tests
          environment:
            PYTHONPATH: /root/project
          command: env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/liboqs/build/lib python3 -m nose --rednose --verbose

workflows:
  version: 2.1
  build:
    jobs:
      - ubuntu_bionic:
          name: ubuntu-bionic
          context: openquantumsafe
